### ISSUE TITLE
Calendar page: design edits

### ISSUE THREAD

**Issue by emanelfy** [cds-snc/ircc-rescheduler#135]
**Overall Changes:**
- [x] back link
- [x] calendar arrows
- [ ] removing weekends
- [x] error messaging

--

## Back link
Should remain fixed to the top of the page, even when scrolling. 

1. remove underline beneath the arrow
![img_6014](https://user-images.githubusercontent.com/35348560/41065976-557fcc5c-69ae-11e8-8658-957dbbf3407e.jpg)

2. change the arrow icon + sentence case for "Go back"
<img width="591" alt="screen shot 2018-06-06 at 5 24 55 pm" src="https://user-images.githubusercontent.com/35348560/41066043-8ee040ee-69ae-11e8-9099-9f0c07470895.png">

3. increase overall size

-- 

## Calendar: arrows
Should be bigger, and look like this, in full **black**... _(+ the dotted line on the calendar should be 50% black)_
<img width="896" alt="screen shot 2018-06-06 at 5 26 24 pm" src="https://user-images.githubusercontent.com/35348560/41066115-cf767786-69ae-11e8-9473-5745ca56144d.png">

--

## Removing weekends
We don't need them, and this will enable a larger calendar display.
          _Potential to change 'day of the week' headers to three characters instead of two._
<img width="532" alt="screen shot 2018-06-06 at 5 29 37 pm" src="https://user-images.githubusercontent.com/35348560/41066253-4b426352-69af-11e8-92b8-6975764030da.png">

-- 

## Error messaging
1. When the user is viewing the calendar, the error is out of view. Page needs to jump up to where this error can actually be seen. 
<img width="286" alt="screen shot 2018-06-06 at 9 43 26 pm" src="https://user-images.githubusercontent.com/35348560/41073784-d5d5b5fa-69d2-11e8-813c-96cda6b24d00.png">

2. Remove the exclamation mark.
<img width="290" alt="screen shot 2018-06-06 at 5 51 10 pm" src="https://user-images.githubusercontent.com/35348560/41067075-3f892af2-69b2-11e8-91a9-eb82f71b6736.png">

**Comment by kyliehavelock** [comment]
- What pixel size should the 'Go back' link be? 
- What pixel size should the calendar month arrows be?

**Comment by kyliehavelock** [comment]
Other comments from the [design review](https://docs.google.com/document/d/1tInLMODBMwkK7mXJ0foVr5gvKxuw617_Bw8Dmu50mKw/edit#heading=h.ytjqhm1i0sqk)

- Alert: icon floats above text, text rag and wrapping are off
- Alpha banner/GC branding/header take up too much space
- Error messaging: Exclamation seems unnecessary. It comes across as alarming rather than friendly.

**Comment by zakkain** [comment]
Will update Calendar error strings here for:
- "too many dates" error
- "too few dates selected" error

**Comment by emanelfy** [comment]
Go back link will be the same size as the main copy on that page (as discussed). 

All arrows in the buttons and on the calendar will be (https://graphemica.com/%E2%9D%AF).

Alert icon + Alpha banner etc, see warning box task here (https://github.com/cds-snc/ircc-rescheduler/issues/130)

Exclamation point comment taken care of above.

**Comment by emanelfy** [comment]
We will look into removing weekends after go live, this is potentially complicated @pcraig3

**Comment by zakkain** [comment]
@pcraig3 I've updated the "too many dates!" error message myself, in my copy polish pass.

However, I can't update the "too few dates!" message because what's live still uses the old "sorry..." box pattern. So here's copy for the "too few!" error that fires when users hit Continue when they've only selected 1 or 2 dates:

`You must select 3 dates. Please select [1 more date | 2 more dates] to continue.`

The error should be dynamic based on how many dates they've selected (1 or 2), hence my square bracket logic notation >_>

**Comment by pcraig3** [comment]
Closing because the we've resolved everything except the weekends, and the original designs have moved on since this. 

If we want to remove weekends in future, that should be a separate issue.
