### ISSUE TITLE
Click error link doesn't navigate unless double clicked

### ISSUE THREAD

**Issue by nschonni** [cds-snc/ircc-rescheduler#177]
Tested on FF 60.
Steps to reproduce
1. Navigate to https://rescheduler.cds-snc.ca/register
1. Click on Continue without submitting any data
1. Click on any of the error links
1. Navigation scrolls to top of page
1. Second click on same link focuses input, but scrolls paste label

Excepted behaviour:
Clicking error link focuses item with error and still shows label for input

**Comment by pcraig3** [comment]
Hey, these should both have been fixed since #250.

Briefly, 

- the error list wasn't being scrolled into view on all browsers (safari >.<) for _reasons_, even though browser focus was being set, so we are now doing that explicitly.

- once the JS kicks in on our react SPA, any anchor links just stop working (not in chrome?? but in other browsers). So, to work around that we turned our boring `<a>`s into `<HashLink>`s.
