### ISSUE TITLE
Data validation on submitting calendar dates 💚

### ISSUE THREAD

**Issue by chowdhurian** [cds-snc/ircc-rescheduler#52]
At https://ircc-poc.azurewebsites.net/calendar, the user is asked to select _at least four days_ to be available for their citizenship tests.

Selecting _fewer_ than four dates still allows the user to progress to the success page.

Good UX practice suggests that the form be validated on the client-side before a request is made to the endpoint.

Then again, the url including `-poc` implies that this is a proof-of-concept, so I apologize if this issue is entirely unhelpful for your open source project! 🙏🏽

<img width="640" alt="screen shot 2018-04-19 at 16 56 13" src="https://user-images.githubusercontent.com/10335475/39024077-644b9b98-43f3-11e8-9b30-6c6b5851bb32.png">

**Comment by pcraig3** [comment]
Hey man, thanks for opening the issue.

Currently the calendar is there to give some sense of the interaction we want (which was useful for testing) but the logic of reading and validating the values hasn't been added in yet.

Here's the current couple of post-it notes about it.

![20180420_211256978_ios](https://user-images.githubusercontent.com/2454380/39074213-832b4c7c-44be-11e8-925d-9356aade0aa7.jpg)

**Comment by pcraig3** [comment]
This is ongoing, and I'll update it when it's in.

**Comment by chowdhurian** [comment]
Thanks for sharing. FWIW, props for making civic projects open source, then actually following up with engagement! 💯

**Comment by pcraig3** [comment]
For sure! Last week was chock-full of other stuff, but we expect to have this resolved this week. 👍

**Comment by pcraig3** [comment]
Hey there, 

New link is here: [http://rescheduler.cds-snc.ca/calendar](http://rescheduler.cds-snc.ca/calendar)

Just a quick follow-up:

- new design includes adding dates to the screen as they're clicked (there is a rudimentary version of this happening now)
- we also want to add some logic so that a maximum of 3 days may be selected
- dates are not yet being passed through to the "review" page

If you would like to open any of those as issues, feel free and I can update them as we go. 
Otherwise, you can just check back in a week or two and see what the progress has been.

**Comment by chowdhurian** [comment]
> new design includes adding dates to the screen as they're clicked (there is a rudimentary version of this happening now)

Nice one. Maybe this has the added benefit of being more accessible.

> If you would like to open any of those as issues, feel free and I can update them as we go.

Sure 👍
