### ISSUE TITLE
Clean up HTML Markup

### ISSUE THREAD

**Issue by Amirroracle** [cds-snc/ircc-rescheduler#78]
Currently there are many Html warnings that need fixing, though some like the following

> The type attribute is unnecessary for JavaScript resources.

can be ignored, but others are more important. This was run only on the homepage, did not include issues from the other pages.

[https://validator.w3.org/nu/?showimagereport=yes&doc=http%3A%2F%2Frescheduler.cds-snc.ca%2F](url)

<img width="1292" alt="screen shot 2018-04-27 at 12 22 40 pm" src="https://user-images.githubusercontent.com/9355166/39373622-23eb1514-4a16-11e8-92a2-155ed1217c77.png">
<img width="969" alt="screen shot 2018-04-27 at 12 26 37 pm" src="https://user-images.githubusercontent.com/9355166/39373653-41774616-4a16-11e8-8c40-edc083572003.png">

**Comment by pcraig3** [comment]
Some of these warnings are things we want to keep around, or they're being automatically generated for us. 
If we're misconfiguring things we should fix that, but if we're doing everything right and there's some library generating a warning, then we don't need to spend too much time on those.

As an example, the `main role="main"` warning is something we are disregarding. [It's not needed for modern browsers, but it's useful for Internet Explorers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#Browser_compatibility).

**Comment by pcraig3** [comment]
Just looked on the calendar page to see what the specific problems are:

## Errors

### 1. Element title not allowed as child of element head in this context
### 2.  Element title must not be empty.

Our page titles aren't really figured out. It would be great to have a server-rendered page-title thing for each page. Otherwise, we're always going to end up with two `<title>`s in the `<head>`.

### 3. CSS: transform: is an incorrect operator

Don't know where this is coming from, but if this is our code is should be easy to fix.

## Warnings 

### 1. Consider adding a lang attribute to the html start tag to declare the language of this document

The `lang` attribute tells screenreaders what language to expect the body text to be in. If it changes while they are on the page, then the screenreader may not know that this has changed. We may need to force a full-page reload when the language is changed to get around this.

But even if we don't we need to be able to change the attribute back and forth as users switch between english and french. 

### 3. The charset attribute on the script element is obsolete.
### 4. The type attribute is unnecessary for JavaScript resources.

This is being generated outside of our code and they're just warnings so we don't care.

### 5. Section lacks heading

Easy to fix these. We should add headings or turn them into `div`s when there there is no heading needed.

### 6.  The main role is unnecessary for element main.

This is a fallback for older browsers. It's not an error, so we can just leave it alone.

**Comment by Amirroracle** [comment]
Element titles are an issue atm, was looking into it with Mike yesterday and we got it working with the Helmet component. The problem then came when we tried to translate the title since:

```
<Helmet>
<title><Trans>Text< /Trans></title>
</Helmet>
```

Helmet will throw an error because it is expecting a string but it is getting back a Translation object.
https://github.com/nfl/react-helmet/issues/326

**Comment by pcraig3** [comment]
Gonna close this issue because our markup has moved on a lot since then.

# Progress 
- [x] Element title not allowed as child of element head in this context 
  -- **we aren't really doing page titles at the minute**
- [x] Element title must not be empty
  -- **ditto**
- [x] CSS: transform: is an incorrect operator 
  -- **fixed**

- [ ] Consider adding a lang attribute to the html start tag to declare the language of this document
  -- **not fixed, but it will be as part of our #128 issue**

-  [x] The charset attribute on the script element is obsolete.
  -- **fixed**

-  [ ] The type attribute is unnecessary for JavaScript resources.
  -- **autogenerated, so we can't change it easily**

-  [x]  Section lacks heading
  -- **fixed**

-  [ ]  The main role is unnecessary for element main.
  -- **we are keeping this in on purpose**

We also have one more error: "Element style not allowed as child of element label in this context". It's complaining about a `<style>` tag being inside of a label. This is more autogenerated code, so we can't change it easily. But, in a practical sense, it's not something any accessibility device will care about or any browser will mind.
