### ISSUE TITLE
Code coverage for what has and has not been tested.

### ISSUE THREAD

**Issue by Amirroracle** [cds-snc/ircc-rescheduler#84]
##  Here is the code coverage report by Jest which shows what has or has not been tested yet.

![screen shot 2018-04-30 at 3 14 27 pm](https://user-images.githubusercontent.com/9355166/39445529-4861f0fa-4c89-11e8-9e45-d18d4abe53c3.png)

**Comment by pcraig3** [comment]
This is more useful for us as an rough estimate rather than something we should be following dogmatically.

For example:
- `createApolloClient.js` gets a low mark for test coverage but it seems pretty low-risk to me. Once we can see that the queries are working, I'm not sure exactly how we would want to test this.
- `CalendarPage.js` says it's 100% tested but really it isn't

Although there are some good points in here. For example, the 404 page is something we could easily have a test for.

**Comment by Amirroracle** [comment]
I agree, don't want to use this as some sort of holy grail, more as a rough guideline as to what needs tests at the moment. The 404 page for example is one that does.
